### ISSUE TITLE
Is there a way to support multiline values?

### ISSUE THREAD

**Issue by kiriakos** [iamtheyammer/branch-env-vars#12]
Hi, thanks for creating this action, I have been using it quite successfully in the past months. Today I stumbled on an error when one of the secrets I was interpolating into the values contained newlines. Is there a way to work around this?

```yaml
jobs:
  deploy:
    steps:
     - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.1.3
        with:
          WORKING_SEC: |
            main:${{ secrets.PRODUCTION_SECRET }}
            develop:${{ secrets.DEVELOPMENT_SECRET }}
            staging:${{ secrets.STAGING_SECRET }}
          NEWLINE_SEC: |
            main:${{ secrets.PRODUCTION_SECRET_W_NEWLINE }}
            develop:${{ secrets.DEVELOPMENT_SECRET_W_NEWLINE }}
            staging:${{ secrets.STAGING_SECRET_W_NEWLINE }}
```

If the values to the secrets have newlines, eg: `secrets.PRODUCTION_SECRET_W_NEWLINE` contains 
```

hello
world
```

the step will fail with the error message: `Error: Invalid value for NEWLINE_SEC: *** does not contain a colon`
