### ISSUE TITLE
How to consume the variable and use in other place?

### ISSUE THREAD

**Issue by bannarisoftwares** [iamtheyammer/branch-env-vars#17]
Here i am trying to consume the value of EXAMPLE. How to consume and ssign the value.. Please update this step in document

```
steps:
      - name: Branch-based environment variables that rock
        uses: iamtheyammer/branch-env-vars@v1.2.0
        with:
          EXAMPLE: |
            master:valueformaster
            staging:valueforstaging
      - name: Create annotation for build error
        run: echo "${{EXAMPLE}}"
```
