### ISSUE TITLE
Getting warning as Unexpected input(s) 'ENV_NAME', valid inputs are ['bevOverwrite', 'bevActionOnNoRef', 'bevSetEmptyVars']

### ISSUE THREAD

**Issue by bannarisoftwares** [iamtheyammer/branch-env-vars#23]
Getting error for 
```
Unexpected input(s) 'ENV_NAME', valid inputs are ['bevOverwrite', 'bevActionOnNoRef', 'bevSetEmptyVars']
```
 

Example:

```   
   
      - name: Branch-based environment variables that rock
        uses: iamtheyammer/branch-env-vars@v1.2.2
        with:
          bevOverwrite: true
          ENV_NAME: |
            dev:dev
            prod:prod
            
```
