### ISSUE TITLE
How to access the variable set in one step to another step?

### ISSUE THREAD

**Issue by bishal-insight** [iamtheyammer/branch-env-vars#9]
I am working on a project, for this I need a branch based environment variable. I tried to implement as 

```
- name: Set the variables
  uses: iamtheyammer/branch-env-vars@v1.0.4
      with:
         SECRET_KEY: |
            development:${{ secrets.SECRET_KEY }}
          CHECKVAR: |
            development:"hi i am checkvar"
        
- name : Test by python
  run: |
      echo "start of echo :"
      echo "$SECRET_KEY"
      echo "$CHECKVAR"
      echo "end of echo"
```

I am not able to see the output of echo in the next step. I think the variable set are not passed to the next step. Am I doing it wrong or is there any step to pass variable to the next step. I tried to implement ``` run echo "var_name=VALUE" >> $GITHUB_ENV```. I am not able to run it inside the with block. Please tell me the proper way of using it.

**Comment by iamtheyammer** [comment]
Are you on the development branch? Those variables are only present on the development branch.

**Comment by bishal-insight** [comment]
Hello Sam. I wasnot able to access the variable in the development branch.  In the above case output  of echo "$CHECKVAR" is empty in development branch.

**Comment by irl-dan** [comment]
Yes, fairly sure this is expected Github Actions behavior, environment variables aren't saved across steps. Which leaves me wondering how anyone uses this plugin at all?

**Comment by rvdlaarschot** [comment]
Environment variables are persistent across steps (not across jobs, that is another topic). To retrieve them in through bash script your formatting will not work, you need to explicitly call the environment context through an expression. I got it to work by using the below code. Please note that the secret value will be printed as ***. Hope this helps!
```
     - name: Set the variables
        uses: iamtheyammer/branch-env-vars@v1.0.4
        with:
          SECRET_KEY: |
            development:${{ secrets.SECRET_KEY }}
          CHECKVAR: |
            development:"hi i am checkvar"

      - name: Test by python
        run: |
          echo "start of echo :"
          echo "${{ env.SECRET_KEY }}"
          echo "${{ env.CHECKVAR }}"
          echo "end of echo"
```

**Comment by hero-david** [comment]
Hi @rvdlaarschot, unfortunately that's slightly mistaken. This step uses the GitHub actions core Javascript library to set the env vars:
https://github.com/iamtheyammer/branch-env-vars/blob/master/src/index.js#L172

That function writes variable values to the GITHUB_ENV file which is loaded into the env with each step:
https://github.com/actions/toolkit/blob/dd046652c32b45c0207b37ee0bc0ebf43a28b257/docs/commands.md#set-an-environment-variable

Thus it is readable via the `env.` context as well as the shell environment, and something like this works:
```yaml
name: "Test"

on: [ "push" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Variables
      uses: iamtheyammer/branch-env-vars@v1.0.4
      with:
        SECRET_KEY: |
          main:${{ secrets.SECRET_KEY }}
        CHECKVAR: |
          main:"hi i am checkvar"
    - name: Test
      run: |
        echo "start of echo :"
        echo "$SECRET_KEY"
        echo "$CHECKVAR"
        echo "end of echo"
```

As can be seen on this GitHub actions run:
https://github.com/hero-david/demo-branch-env-vars/runs/7601243111?check_suite_focus=true

I found this thread because I was looking for answers around unset vars, and realised I was just on the wrong branch (It had been a long day!). @bishal-insight Worth -double- triple checking that, but it might also be worth examining the seemingly incorrect formatting of the with statement in your example

```yaml
- name: Set the variables
  uses: iamtheyammer/branch-env-vars@v1.0.4
      with:
         SECRET_KEY: |
```

With blocks need to be at the same level as the `uses:` key per my example above :+1: 

It probably also helps to click  `Re-run all jobs` and then click `Enable debug logging` and include those logs to get a better understanding of what is going on and include those in issues :-) 

There is also very good output included in the drop down by default, allowing you to see if a variable has 'hit' or not, and whether the `with: block has been picked up by the action:
![image](https://user-images.githubusercontent.com/108767410/182045073-3102731e-7649-48ca-96ad-5c38f35ab95b.png)


Hope this somewhat helps people in future, thanks for the plugin @iamtheyammer! Has made setting certain values across branches a trivial pursuit :heart:

**Comment by iamtheyammer** [comment]
Huge thanks to @hero-david for your fantastic writeup and @rvdlaarschot for mentioning the `${{ env.XXX }}` syntax and for pointing out that variables are persistent on subsequent steps in **the same job**, however they're not exactly in the shell environment. If you need them to be in the shell environment, you'll need steps like this (as shown in docs [here](https://docs.github.com/en/actions/learn-github-actions/environment-variables#about-environment-variables)):

```yaml
     - name: Set the variables
        uses: iamtheyammer/branch-env-vars@...
        with:
          SECRET_KEY: |
            development:${{ secrets.SECRET_KEY }}
          CHECKVAR: |
            development:"hi i am checkvar"

      - name: Test by python
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          CHECKVAR: ${{ env.CHECKVAR }}
        run: |
          echo "start of echo :"
          echo "$SECRET_KEY"
          echo "$CHEKVAR"
          echo "end of echo"
```
Note the `env` section in the `Test by python` step.

Just a couple of things to mention before I close this issue:
- @rvdlaarschot: in your example, you put the value for `CHECKVAR` on the `development` branch in quotes-- note that those quotes will be present in the final, exported value-- they aren't stripped out.
- @bishal-insight: for anyone reading this in the future trying to use `echo "var_name=VALUE" >> $GITHUB_ENV` to add environment variables, this is **no longer supported**. You need to use `echo "{environment_variable_name}={value}" >> $GITHUB_ENV`, as mentioned [here in the GitHub docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable).
